@ApiGateway_HostAddress = https://localhost:7282

### Health Check - API Gateway
GET {{ApiGateway_HostAddress}}/health
Accept: application/json

### Test User Service Route
GET {{ApiGateway_HostAddress}}/users-service/api/users
Accept: application/json

### Test Order Service Route
GET {{ApiGateway_HostAddress}}/orders-service/api/orders
Accept: application/json

### Test Payment Service Route
GET {{ApiGateway_HostAddress}}/payments-service/api/payments
Accept: application/json

### Swagger UI
GET {{ApiGateway_HostAddress}}/swagger
